### ISSUE TITLE
LevelSelect issue with Shop

### ISSUE THREAD

**Issue by Cstumbough** [paux86/TBD2-JudgementDay#84]
Upon clearing the 4th level, if you go to the shop, upon leaving the shop you will be locked out of the next levels, rendering you unable to play the game
![TBD2-BeforeShopButton](https://user-images.githubusercontent.com/59980214/80559281-eac0f980-8991-11ea-87f5-56e692660116.png)
![TBD2-AfterShopButton](https://user-images.githubusercontent.com/59980214/80559286-f0b6da80-8991-11ea-9c6c-7da38c5aedb7.png)

**Comment by Bombg** [comment]
moved shop scene to the regular map progression, so this bug shouldn't exist anymore
